import { Injectable }     from '@angular/core';
@Injectable()
export class TeamSimpel {
    constructor (public teamname: string,
                   public fieldnameshort: string,
                   public clubnameshort: string,
                   public rower8: string,
                   public rower7: string,
                   public rower6: string,
                   public rower5: string,
                   public rower4: string,
                   public rower3: string,
                   public rower2: string,
                   public rower1: string,
                   public steername: string,
                   public coachname: string,
                   public excluded: string,
                   public disqualified: string,
                   public raceid: string,
                   public backnumber: string,
                   public totaltime: string,
                   public splash1: string,
                   public splash2: string,
                   public splash3: string,
                   public splash4: string,
                   public isapproved: string,
                   public bonusseconds: string,
                   public comments: string,
                   public time: string,
                   public fieldnameshortsub: string,
                   public rank: string,
                   public participants: string,
                   public clubname: string) {}
}